// 06_搭建React项目开发环境_ts版/src/components/CssCom/index.tsx
import React, { memo } from 'react'
import { increment, decrement } from '@/store/features/counter'
import { useAppDispatch } from '@/store/hooks'
import './index.css'

interface Props {
  type: string
}

const CssDom: React.FC<Props> = memo((props) => {
  const { type } = props

  const dispatch = useAppDispatch()

  return (
    <div>
      <h2 className="css">
        测试{type}文件是否<span>正常加载</span>
      </h2>
      <button onClick={() => dispatch(increment())}>count++</button>
      <button onClick={() => dispatch(decrement())}>count--</button>
    </div>
  )
})

export default CssDom

// 03_搭建Vue3项目的开发环境_js版/src/components/CssCom.vue
<template>
  <h2 class="css">测试{{ type }}文件是否<span>正常加载</span></h2>
  <button @click="increment">count++</button>
  <button @click="decrement">count--</button>
</template>

<script setup>
import { useCounterStore } from '@/store'

defineProps({
  type: String
})

const counterStore = useCounterStore()
const { increment, decrement } = counterStore
</script>

<style scoped>
.css {
  color: red;
  span {
    font-size: 30px;
    color: blue;
  }
}
</style>
