// 05_搭建React项目开发环境_js版/src/components/LessCom/index.jsx
import React, { memo } from 'react'
import { useSelector, shallowEqual, useDispatch } from 'react-redux'
import { changeInfo as change } from '@/store/userInfo'
import './index.less'

const LessCom = memo(({ type }) => {
  const { name, age } = useSelector((state) => state.userInfo, shallowEqual)
  const dispatch = useDispatch()

  const changeInfo = () => {
    dispatch(
      change({
        age: age + 1
      })
    )
  }

  return (
    <>
      <h2 className="less">
        测试{type}文件是否<span>正常加载</span>
      </h2>
      <h3>
        name: {name} age: {age}
      </h3>
      <button onClick={changeInfo}>age++</button>
    </>
  )
})

export default LessCom

// 03_搭建Vue3项目的开发环境_js版/src/components/LessCom.vue
<template>
  <h2 class="less">测试{{ type }}文件是否<span>正常加载</span></h2>
  <h3>name: {{ userInfo.name }} age: {{ userInfo.age }}</h3>
  <button @click="changeInfo">age++</button>
</template>

<script setup>
import { storeToRefs } from 'pinia'
import { useUserInfoStore } from '@/store'

defineProps({
  type: String
})

const userInfoStore = useUserInfoStore()
const { userInfo } = storeToRefs(userInfoStore)

const changeInfo = () => {
  userInfo.value.age++
}
</script>

<style scoped lang="less">
.less {
  color: blue;
  span {
    color: red;
  }
}
</style>
