// 04_搭建Vue3项目的开发环境_ts版/src/components/ScssCom.vue
<template>
  <h2 class="scss">测试{{ type }}文件是否<span>正常加载</span></h2>
  <h3>name: {{ userInfo.name }} age: {{ userInfo.age }}</h3>
  <button @click="updateInfo({ name: 'vue' })">更改姓名</button>
</template>

<script setup lang="ts">
import { storeToRefs } from 'pinia'
import { useUserInfoStore } from '@/store'

interface PropsTypes {
  type: string
}

defineProps<PropsTypes>()

const userInfoStore = useUserInfoStore()
const { userInfo } = storeToRefs(userInfoStore)
const { updateInfo } = userInfoStore
</script>

<style scoped lang="scss">
.scss {
  color: red;
  span {
    font-size: 30px;
    color: blue;
  }
}
</style>

// 05_搭建React项目开发环境_js版/src/components/ScssCom/index.jsx
import React, { memo } from 'react'
import { useSelector, shallowEqual, useDispatch } from 'react-redux'
import { changeInfo } from '@/store/userInfo'
import './index.scss'

const ScssCom = memo(({ type }) => {
  const userInfo = useSelector((state) => state.userInfo, shallowEqual)
  const dispatch = useDispatch()

  return (
    <>
      <h2 className="scss">
        测试{type}文件是否<span>正常加载</span>
      </h2>
      <h3>
        name: {userInfo.name} age: {userInfo.age}
      </h3>
      <button onClick={() => dispatch(changeInfo({ name: 'react' }))}>
        更改姓名
      </button>
    </>
  )
})

export default ScssCom
