// 05_搭建React项目开发环境_js版/src/App.jsx
import React, { memo } from 'react'
import { NavLink, Outlet } from 'react-router-dom'
import { CssCom, LessCom, SassCom, ScssCom } from '@/components'
import './index.less'

const App = memo(() => {
  return (
    <div className="app">
      <h1>React + React-router + Redux + RTK</h1>
      <CssCom type="css" />
      <LessCom type="less" />
      <ScssCom type="scss" />
      <SassCom type="sass" />
      <nav>
        <NavLink to="/">HOME</NavLink>
        <NavLink to="/about">ABOUT</NavLink>
        <NavLink to="/article">ARTICLE</NavLink>
      </nav>
      <main>
        <Outlet />
      </main>
    </div>
  )
})

export default App

// 04_搭建Vue3项目的开发环境_ts版/src/App.vue
<template>
  <div class="vue">
    <h1>Hello Vue</h1>
    <div class="count">
      <button @click="count++">+1</button>
      <h2>{{ count }}</h2>
      <button @click="count--">-1</button>
    </div>
    <CssCom type="css" />
    <LessCom type="less" />
    <SassCom type="sass" />
    <ScssCom type="scss" />
    <Layout />
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { CssCom, LessCom, SassCom, ScssCom, Layout } from '@/components'

const count = ref<number>(10)
</script>

<style scoped lang="less">
.vue {
  .count {
    height: 30px;
    display: flex;
    align-items: center;
    h2 {
      margin: 0 10px;
    }
  }
}
</style>
