// 06_搭建React项目开发环境_ts版/src/components/CreateImage/index.tsx
import React, { memo } from 'react'
import { Styled } from './style'

interface Props {
  name: string
  url: string
}

const CreateImage: React.FC<Props> = memo((props) => {
  const { name, url } = props

  return (
    <Styled>
      <div>插入的图片名称：{name}</div>
      <img src={url} alt={name} />
    </Styled>
  )
})

export default CreateImage

// 04_搭建Vue3项目的开发环境_ts版/src/components/CreateImage.vue
<template>
  <div class="create-img">
    插入的图片名称：{{ name }}
    <br />
    <img :src="url" :alt="name" />
  </div>
</template>

<script lang="ts" setup>
interface PropsTypes {
  name: string
  url: string
}
defineProps<PropsTypes>()
</script>

<style scoped lang="less">
.create-img {
  img {
    width: 200px;
    height: 200px;
  }
}
</style>
